name: 522groupenv.yaml
channels:
  - conda-forge
  - defaults
dependencies:
  - numpy=1.26.4
  - pandas=2.3.3
  - python=3.12
  - scikit-learn=1.7.2
  - ucimlrepo=0.0.7
  - jupyter=1.1.1
  - matplotlib=3.10.8
  - altair=6.0.0
  - vegafusion=1.6.9
  - vl-convert-python=1.8.0
  - pyarrow=22.0.0
  - conda-lock=3.0.4
  - pointblank=0.16.0
  - pytest=9.0.2
  - make   
